/* ── Translations for KisanSetu ── */
export const T = {
  en: {
    greeting: (n) => `Ram Ram, ${n}!`,
    sub: "Welcome back to your farm's digital companion.",
    tapSpeak: "Tap to speak in English or Hindi",
    voicePlaceholder: '"Should I water my crops today?"',
    listening: "Listening...",
    thinking: "Thinking...",
    alertTitle: "High Humidity Alert",
    alertMsg: "Do not irrigate Paddy today. Check for brown spots on lower leaves.",
    weather: "WEATHER",
    waterBudget: "Water Budget",
    soilMoisture: "Soil Moisture",
    pestCheck: "PEST CHECK",
    scanCrop: "SCAN CROP",
    markets: "MARKETS",
    soilHealth: "SOIL HEALTH",
    nitrogenOk: "Nitrogen Levels Optimal",
    viewReport: "View Lab Report",
    community: "Community Updates",
    upcomingEvent: "Upcoming Event",
    eventTitle: "Village Organic Workshop - Sat 10 AM",
    eventSub: "Join 12 others from Pune Mandi.",
    home: "Home",
    voice: "Voice",
    scan: "Scan",
    market: "Market",
    hold: "HOLD",
    sell: "SELL NOW",
    analyzing: "Analyzing leaf...",
    pestResult: "Diagnosis",
    playVoice: "Play Advisory",
    good: "Good",
    low: "Low",
    critical: "Critical",
    getAdvisory: "Get Advisory",
    loading: "Analyzing farm data...",
    yieldEst: "Yield Estimate",
    area: "Area (acres)",
    takePhoto: "Take / Upload Leaf Photo",
    tapCamera: "Tap to open camera or gallery",
    voiceAdvisory: "Voice Advisory",
    voiceAdvisorySub: "Speak your question or get an instant advisory.",
    pestTitle: "Pest & Disease Scan",
    pestSub: "Take a photo of a leaf to get an AI diagnosis.",
    marketTitle: "Market & Yield",
    marketSub: "Mandi prices, sell/hold advice, and yield estimator.",
    todayAdvisory: "Today's Advisory",
    commonIssues: "Common Issues",
    nearbyMandis: "Nearby Mandis",
    estimateYield: "Estimate Yield",
    estimating: "Estimating...",
    localMandi: "Local Mandi",
    sellAdvice: "Price likely to fall - sell within 2 days",
    holdAdvice: "Forecasted rise - holding recommended",
    holdDays: "days",
    setupSub: "Set up your farm profile to get started",
    yourName: "Your Name",
    namePlaceholder: "e.g. Ramesh",
    yourLocation: "Your Location",
    selectLocation: "Select your district",
    primaryCrop: "Primary Crop",
    getStarted: "Get Started",
    changeLocation: "Change Location",
  },
  hi: {
    greeting: (n) => `राम राम, ${n}!`,
    sub: "आपके खेत के डिजिटल साथी में वापस स्वागत है।",
    tapSpeak: "हिंदी या मराठी में बोलें",
    voicePlaceholder: '"क्या आज सिंचाई करनी चाहिए?"',
    listening: "सुन रहा हूं...",
    thinking: "सोच रहा हूं...",
    alertTitle: "उच्च आर्द्रता चेतावनी",
    alertMsg: "आज धान की सिंचाई न करें। निचली पत्तियों पर भूरे धब्बे देखें।",
    weather: "मौसम",
    waterBudget: "पानी बजट",
    soilMoisture: "मिट्टी नमी",
    pestCheck: "कीट जांच",
    scanCrop: "फसल स्कैन",
    markets: "मंडी",
    soilHealth: "मिट्टी स्वास्थ्य",
    nitrogenOk: "नाइट्रोजन स्तर उचित",
    viewReport: "रिपोर्ट देखें",
    community: "सामुदायिक अपडेट",
    upcomingEvent: "आगामी कार्यक्रम",
    eventTitle: "गांव जैविक कार्यशाला - शनि 10 बजे",
    eventSub: "पुणे मंडी के 12 अन्य किसानों से जुड़ें।",
    home: "होम",
    voice: "आवाज़",
    scan: "स्कैन",
    market: "मंडी",
    hold: "रोकें",
    sell: "अभी बेचें",
    analyzing: "पत्ती जांच रहे हैं...",
    pestResult: "निदान",
    playVoice: "सलाह सुनें",
    good: "अच्छा",
    low: "कम",
    critical: "गंभीर",
    getAdvisory: "सलाह लें",
    loading: "खेत डेटा विश्लेषण...",
    yieldEst: "उपज अनुमान",
    area: "क्षेत्र (एकड़)",
    takePhoto: "पत्ती का फोटो लें / अपलोड करें",
    tapCamera: "कैमरा या गैलरी खोलने के लिए टैप करें",
    voiceAdvisory: "आवाज़ सलाह",
    voiceAdvisorySub: "अपना सवाल बोलें या तुरंत सलाह पाएं।",
    pestTitle: "कीट और रोग स्कैन",
    pestSub: "AI निदान के लिए पत्ती का फोटो लें।",
    marketTitle: "मंडी और उपज",
    marketSub: "मंडी भाव, बेचें/रोकें सलाह, और उपज अनुमान।",
    todayAdvisory: "आज की सलाह",
    commonIssues: "सामान्य समस्याएं",
    nearbyMandis: "आस-पास की मंडियां",
    estimateYield: "उपज अनुमान",
    estimating: "अनुमान लगा रहे हैं...",
    localMandi: "स्थानीय मंडी",
    sellAdvice: "भाव गिरने की संभावना - 2 दिन में बेचें",
    holdAdvice: "भाव बढ़ने का अनुमान - रोकें",
    holdDays: "दिन",
    setupSub: "शुरू करने के लिए अपना खेत प्रोफाइल सेट करें",
    yourName: "आपका नाम",
    namePlaceholder: "जैसे रमेश",
    yourLocation: "आपका स्थान",
    selectLocation: "अपना जिला चुनें",
    primaryCrop: "मुख्य फसल",
    getStarted: "शुरू करें",
    changeLocation: "स्थान बदलें",
  },
  mr: {
    greeting: (n) => `राम राम, ${n}!`,
    sub: "तुमच्या शेताच्या डिजिटल साथीमध्ये परत स्वागत आहे।",
    tapSpeak: "मराठी किंवा हिंदीत बोला",
    voicePlaceholder: '"आज पाणी द्यायचे का?"',
    listening: "ऐकत आहे...",
    thinking: "विचार करत आहे...",
    alertTitle: "उच्च आर्द्रता इशारा",
    alertMsg: "आज भात सिंचन करू नका. खालच्या पानांवर तपकिरी डाग तपासा.",
    weather: "हवामान",
    waterBudget: "पाणी बजेट",
    soilMoisture: "माती ओलावा",
    pestCheck: "कीड तपासणी",
    scanCrop: "पीक स्कॅन",
    markets: "मंडी",
    soilHealth: "माती आरोग्य",
    nitrogenOk: "नायट्रोजन पातळी योग्य",
    viewReport: "अहवाल पहा",
    community: "समुदाय अपडेट",
    upcomingEvent: "येणारा कार्यक्रम",
    eventTitle: "गाव सेंद्रिय कार्यशाळा - शनि सकाळी 10",
    eventSub: "पुणे मंडीतील 12 इतर शेतकऱ्यांसोबत या.",
    home: "होम",
    voice: "आवाज",
    scan: "स्कॅन",
    market: "मंडी",
    hold: "थांबा",
    sell: "आत्ता विका",
    analyzing: "पान तपासत आहे...",
    pestResult: "निदान",
    playVoice: "सल्ला ऐका",
    good: "चांगले",
    low: "कमी",
    critical: "गंभीर",
    getAdvisory: "सल्ला घ्या",
    loading: "शेत डेटा विश्लेषण...",
    yieldEst: "उत्पन्न अंदाज",
    area: "क्षेत्र (एकर)",
    takePhoto: "पानाचा फोटो घ्या / अपलोड करा",
    tapCamera: "कॅमेरा किंवा गॅलरी उघडण्यासाठी टॅप करा",
    voiceAdvisory: "आवाज सल्ला",
    voiceAdvisorySub: "तुमचा प्रश्न बोला किंवा त्वरित सल्ला मिळवा.",
    pestTitle: "कीड आणि रोग स्कॅन",
    pestSub: "AI निदानासाठी पानाचा फोटो घ्या.",
    marketTitle: "मंडी आणि उत्पन्न",
    marketSub: "मंडी भाव, विक्री/थांबा सल्ला, आणि उत्पन्न अंदाज.",
    todayAdvisory: "आजचा सल्ला",
    commonIssues: "सामान्य समस्या",
    nearbyMandis: "जवळच्या मंडी",
    estimateYield: "उत्पन्न अंदाज",
    estimating: "अंदाज लावत आहे...",
    localMandi: "स्थानीय मंडी",
    sellAdvice: "भाव गिरण्याची शक्यता - 2 दिवसात विका",
    holdAdvice: "भाव वाढण्याचा अंदाज - थांबा",
    holdDays: "दिवस",
    setupSub: "सुरू करण्यासाठी तुमचे शेत प्रोफाइल सेट करा",
    yourName: "तुमचे नाव",
    namePlaceholder: "उदा. रमेश",
    yourLocation: "तुमचे स्थान",
    selectLocation: "तुमचा जिल्हा निवडा",
    primaryCrop: "मुख्य पीक",
    getStarted: "सुरू करा",
    changeLocation: "स्थान बदला",
  },
  kn: {
    greeting: (n) => `ನಮಸ್ಕಾರ, ${n}!`,
    sub: "ನಿಮ್ಮ ಜಮೀನಿನ ಡಿಜಿಟಲ್ ಸಂಗಾತಿಗೆ ಮರಳಿ ಸ್ವಾಗತ.",
    tapSpeak: "ಕನ್ನಡ ಅಥವಾ ಹಿಂದಿಯಲ್ಲಿ ಮಾತನಾಡಿ",
    voicePlaceholder: '"ಇಂದು ನೀರು ಹಾಕಬೇಕೇ?"',
    listening: "ಕೇಳುತ್ತಿದ್ದೇನೆ...",
    thinking: "ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...",
    alertTitle: "ಹೆಚ್ಚಿನ ಆರ್ದ್ರತೆ ಎಚ್ಚರಿಕೆ",
    alertMsg: "ಇಂದು ಭತ್ತಕ್ಕೆ ನೀರು ಹಾಕಬೇಡಿ. ಕೆಳಗಿನ ಎಲೆಗಳಲ್ಲಿ ಕಂದು ಕಲೆ ಪರೀಕ್ಷಿಸಿ.",
    weather: "ಹವಾಮಾನ",
    waterBudget: "ನೀರಿನ ಬಜೆಟ್",
    soilMoisture: "ಮಣ್ಣಿನ ತೇವ",
    pestCheck: "ಕೀಟ ತಪಾಸಣೆ",
    scanCrop: "ಬೆಳೆ ಸ್ಕ್ಯಾನ್",
    markets: "ಮಂಡಿ",
    soilHealth: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    nitrogenOk: "ಸಾರಜನಕ ಮಟ್ಟ ಸರಿಯಾಗಿದೆ",
    viewReport: "ವರದಿ ನೋಡಿ",
    community: "ಸಮುದಾಯ ಅಪ್‌ಡೇಟ್",
    upcomingEvent: "ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮ",
    eventTitle: "ಗ್ರಾಮ ಸಾವಯವ ಕಾರ್ಯಾಗಾರ - ಶನಿ ಬೆಳಿಗ್ಗೆ 10",
    eventSub: "ಪುಣೆ ಮಂಡಿಯ 12 ರೈತರೊಂದಿಗೆ ಸೇರಿ.",
    home: "ಹೋಮ್",
    voice: "ಧ್ವನಿ",
    scan: "ಸ್ಕ್ಯಾನ್",
    market: "ಮಂಡಿ",
    hold: "ಕಾಯಿರಿ",
    sell: "ಈಗ ಮಾರಿ",
    analyzing: "ಎಲೆ ಪರೀಕ್ಷಿಸುತ್ತಿದ್ದೇನೆ...",
    pestResult: "ರೋಗನಿರ್ಣಯ",
    playVoice: "ಸಲಹೆ ಕೇಳಿ",
    good: "ಉತ್ತಮ",
    low: "ಕಡಿಮೆ",
    critical: "ತೀವ್ರ",
    getAdvisory: "ಸಲಹೆ ಪಡೆಯಿರಿ",
    loading: "ಜಮೀನು ಡೇಟಾ ವಿಶ್ಲೇಷಣೆ...",
    yieldEst: "ಇಳುವರಿ ಅಂದಾಜು",
    area: "ಪ್ರದೇಶ (ಎಕರೆ)",
    takePhoto: "ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ / ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    tapCamera: "ಕ್ಯಾಮೆರಾ ಅಥವಾ ಗ್ಯಾಲರಿ ತೆರೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    voiceAdvisory: "ಧ್ವನಿ ಸಲಹೆ",
    voiceAdvisorySub: "ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಹೇಳಿ ಅಥವಾ ತಕ್ಷಣದ ಸಲಹೆ ಪಡೆಯಿರಿ.",
    pestTitle: "ಕೀಟ ಮತ್ತು ರೋಗ ಸ್ಕ್ಯಾನ್",
    pestSub: "AI ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ.",
    marketTitle: "ಮಂಡಿ ಮತ್ತು ಇಳುವರಿ",
    marketSub: "ಮಂಡಿ ಬೆಲೆಗಳು, ಮಾರಾಟ/ಕಾಯಿರಿ ಸಲಹೆ, ಮತ್ತು ಇಳುವರಿ ಅಂದಾಜು.",
    todayAdvisory: "ಇಂದಿನ ಸಲಹೆ",
    commonIssues: "ಸಾಮಾನ್ಯ ಸಮಸ್ಯೆಗಳು",
    nearbyMandis: "ಹತ್ತಿರದ ಮಂಡಿಗಳು",
    estimateYield: "ಇಳುವರಿ ಅಂದಾಜು",
    estimating: "ಅಂದಾಜು ಮಾಡುತ್ತಿದ್ದೇನೆ...",
    localMandi: "ಸ್ಥಳೀಯ ಮಂಡಿ",
    sellAdvice: "ಬೆಲೆ ಕುಸಿಯುವ ಸಾಧ್ಯತೆ - 2 ದಿನಗಳಲ್ಲಿ ಮಾರಿ",
    holdAdvice: "ಬೆಲೆ ಏರಿಕೆ ನಿರೀಕ್ಷೆ - ಕಾಯಿರಿ",
    holdDays: "ದಿನಗಳು",
    setupSub: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಜಮೀನು ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    namePlaceholder: "ಉದಾ. ರಮೇಶ",
    yourLocation: "ನಿಮ್ಮ ಸ್ಥಳ",
    selectLocation: "ನಿಮ್ಮ ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ",
    primaryCrop: "ಮುಖ್ಯ ಬೆಳೆ",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    changeLocation: "ಸ್ಥಳ ಬದಲಾಯಿಸಿ",
  },
};

export const LANG_VOICES = { en: "en-IN", hi: "hi-IN", mr: "mr-IN", kn: "kn-IN" };
export const LANG_LABELS = { en: "A", hi: "अ", mr: "म", kn: "ಅ" };
export const LANG_NAMES = { en: "English", hi: "Hindi", mr: "Marathi", kn: "Kannada" };

export const CROPS = ["Paddy", "Wheat", "Cotton", "Onion", "Tomato", "Soybean", "Sugarcane", "Maize"];

export const MANDI_DATA = {
  Paddy:     { price: 2180, msp: 2183, trend: "stable", forecast: 2240, action: "hold", gain: 60 },
  Wheat:     { price: 2310, msp: 2275, trend: "up",     forecast: 2380, action: "hold", gain: 70 },
  Cotton:    { price: 6720, msp: 6620, trend: "down",   forecast: 6500, action: "sell", gain: 0  },
  Onion:     { price: 1500, msp: 800,  trend: "up",     forecast: 1700, action: "hold", gain: 200},
  Tomato:    { price: 820,  msp: 600,  trend: "up",     forecast: 1100, action: "hold", gain: 280},
  Soybean:   { price: 4180, msp: 4600, trend: "down",   forecast: 4050, action: "sell", gain: 0  },
  Sugarcane: { price: 3150, msp: 3050, trend: "stable", forecast: 3200, action: "hold", gain: 50 },
  Maize:     { price: 1870, msp: 1870, trend: "up",     forecast: 1920, action: "hold", gain: 50 },
};

export const WEATHER = {
  temp: 21, humidity: 76, rain: 68, ndvi: 0.61, soilMoisture: 58, soilStatus: "good"
};

export const COMMON_ISSUES = [
  { disease: "Blast Disease", severity: "HIGH", treatment: "0.5% Copper fungicide" },
  { disease: "Brown Plant Hopper", severity: "MEDIUM", treatment: "Imidacloprid 0.3ml/L" },
  { disease: "Sheath Blight", severity: "LOW", treatment: "Validamycin 0.1%" },
];

export const NEARBY_MANDIS = [
  { name: "APMC Pune", delta: -40 },
  { name: "Hubli", delta: 80 },
  { name: "Davangere", delta: -10 },
  { name: "Solapur", delta: 120 },
];

export const AREA_OPTIONS = ["0.5", "1", "2", "5", "10"];

export const LOCATIONS = [
  { id: "pune", name: "Pune", state: "Maharashtra" },
  { id: "nashik", name: "Nashik", state: "Maharashtra" },
  { id: "hubli", name: "Hubli", state: "Karnataka" },
  { id: "davangere", name: "Davangere", state: "Karnataka" },
  { id: "solapur", name: "Solapur", state: "Maharashtra" },
  { id: "kolhapur", name: "Kolhapur", state: "Maharashtra" },
  { id: "belgaum", name: "Belgaum", state: "Karnataka" },
  { id: "sangli", name: "Sangli", state: "Maharashtra" },
];
